import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { DM_Sans, Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import CreateApisWrapper from './Wrappers/CreateApisWrapper'
import { Toaster } from 'sonner'
import Link from 'next/link'
import { Button } from '@/components/ui/button'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
const DMSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
  icons: {
    icon: '/apiorbit.svg',
    shortcut: '/apiorbit.svg',
    apple: '/apiorbit.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={` ${DMSans.variable} antialiased`}>
          <Toaster richColors />
          <header className="flex justify-end items-center p-4 gap-4 h-16 fixed top-0 left-0 right-0 z-50">
            <SignedOut>
              <SignInButton>
                <Button
                  variant="default"
                  className="bg-primary text-primary-foreground font-medium shadow-md border-0"
                >
                  Sign In
                </Button>
              </SignInButton>
              <SignUpButton>
                <Button
                  variant="default"
                  className="bg-primary text-primary-foreground font-medium shadow-md border-0"
                >
                  Sign Up
                </Button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <Button
                variant="default"
                className="bg-primary text-primary-foreground font-medium shadow-md border-0"
              >
                <Link href="/dashboard">
                  Dashboard
                </Link>
              </Button>
              <CreateApisWrapper />
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}