import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { DM_Sans, Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import CreateApisWrapper from './Wrappers/CreateApisWrapper'
import { Toaster } from 'sonner'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { MenuIcon, XIcon } from 'lucide-react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
const DMSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
  icons: {
    icon: '/apiorbit.svg',
    shortcut: '/apiorbit.svg',
    apple: '/apiorbit.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={` ${DMSans.variable} antialiased`}>
          <Toaster richColors />
          <header className="bg-black/20 backdrop-blur-sm fixed top-0 left-0 right-0 z-50 md:static">
            <div className="container flex items-center justify-end p-4 h-16">
              <input type="checkbox" id="menu-toggle" className="hidden peer" />
              
              <label
                htmlFor="menu-toggle"
                className="md:hidden cursor-pointer text-white hover:text-primary"
              >
                <MenuIcon className="h-6 w-6 block peer-checked:hidden" />
                <XIcon className="h-6 w-6 hidden peer-checked:block" />
                <span className="sr-only">Toggle menu</span>
              </label>
              
              <div 
                className="hidden peer-checked:absolute peer-checked:top-16 peer-checked:left-0 peer-checked:right-0 peer-checked:flex peer-checked:flex-col peer-checked:bg-black/80 peer-checked:backdrop-blur-md peer-checked:p-4 peer-checked:gap-4 
                           md:flex md:items-center md:gap-4 md:relative md:top-0 md:bg-transparent md:backdrop-blur-none md:p-0"
              >
                <SignedOut>
                  <SignInButton>
                    <div className="flex flex-col sm:flex-row items-center gap-2 sm:gap-4 w-full md:w-auto">
                      <p className='bg-primary text-white rounded-md p-1 text-xs sm:text-sm md:text-base max-w-[300px] sm:max-w-none text-center sm:text-left'>This application uses free services, please wait for server response.</p>
                      <Button
                        variant="default"
                        className="bg-primary text-primary-foreground font-medium shadow-md border-0 w-full sm:w-auto"
                      >
                        Sign In
                      </Button>
                    </div>
                  </SignInButton>
                  <SignUpButton>
                    <Button
                      variant="default"
                      className="bg-primary text-primary-foreground font-medium shadow-md border-0 w-full sm:w-auto mt-2 sm:mt-0"
                    >
                      Sign Up
                    </Button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <div className="flex flex-col md:flex-row items-center gap-4 w-full md:w-auto">
                    <p className='bg-primary text-white rounded-md p-1 text-xs sm:text-sm md:text-base max-w-[300px] sm:max-w-none text-center md:text-left'>This application uses free services, please wait for server response.</p>
                    <Button
                      variant="default"
                      className="bg-primary text-primary-foreground font-medium shadow-md border-0 w-full md:w-auto"
                    >
                      <Link href="/dashboard">
                        Dashboard
                      </Link>
                    </Button>
                    <div className="w-full md:w-auto">
                      <CreateApisWrapper />
                    </div>
                    <UserButton />
                  </div>
                </SignedIn>
              </div>
            </div>
          </header>
          <main className="pt-16 md:pt-0"> 
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}